services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: primus
      POSTGRES_PASSWORD: primus
      POSTGRES_DB: primus_ehr
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U primus"]
      interval: 5s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/primus_ehr
      KC_DB_USERNAME: primus
      KC_DB_PASSWORD: primus
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: true
    command: start-dev
    ports:
      - "8180:8080"
    depends_on:
      postgres:
        condition: service_healthy

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

  sonarqube:
    image: sonarqube:community
    ports:
      - "9000:9000"
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://postgres:5432/primus_ehr
      SONAR_JDBC_USERNAME: primus
      SONAR_JDBC_PASSWORD: primus
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - sonar_data:/opt/sonarqube/data
      - sonar_extensions:/opt/sonarqube/extensions

volumes:
  pgdata:
  sonar_data:
  sonar_extensions:
