# ---------------------------------------------------------------------------
# s3_uploads.tf — S3 bucket for patient documents and message attachments
#
# Architecture:
#   Browser → pre-signed S3 URL (generated by backend) → S3 direct upload
#   Backend → s3:GetObject to retrieve attachments for download/preview
#
# Lifecycle:
#   0–90 days   : S3 Standard (frequent access)
#   90–2555 days: S3 Standard-IA (infrequent access, ~60% cheaper)
#   > 2555 days : Expire (7 years = HIPAA minimum retention for medical records)
#
# Cost:
#   S3 Standard: $0.023/GB/month
#   S3 Standard-IA: $0.0125/GB/month
#   Lifecycle transitions: $0.01/1,000 objects
#   Demo usage: < 1 GB = ~$0.023/month
# ---------------------------------------------------------------------------

# ---------------------------------------------------------------------------
# S3 Bucket — private, versioned, encrypted
# ---------------------------------------------------------------------------
resource "aws_s3_bucket" "uploads" {
  bucket        = "${local.name_prefix}-${var.uploads_bucket_name}-${data.aws_caller_identity.current.account_id}"
  force_destroy = true # Demo: allow clean teardown even with objects present

  tags = { Name = "${local.name_prefix}-uploads" }
}

# Block all public access — objects are only accessible via pre-signed URLs
resource "aws_s3_bucket_public_access_block" "uploads" {
  bucket                  = aws_s3_bucket.uploads.id
  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

# Versioning — preserves overwritten documents; required for audit trail
resource "aws_s3_bucket_versioning" "uploads" {
  bucket = aws_s3_bucket.uploads.id
  versioning_configuration {
    status = "Enabled"
  }
}

# Server-side encryption — S3-managed keys (SSE-S3); free
# Upgrade to SSE-KMS with a CMK in prod for HIPAA BAA key management
resource "aws_s3_bucket_server_side_encryption_configuration" "uploads" {
  bucket = aws_s3_bucket.uploads.id

  rule {
    apply_server_side_encryption_by_default {
      sse_algorithm = "AES256"
    }
    bucket_key_enabled = false # SSE-S3 does not use bucket keys (KMS-only feature)
  }
}

# ---------------------------------------------------------------------------
# Lifecycle Rules
# HIPAA: medical records must be retained for a minimum of 7 years (2,555 days).
# Non-current versions (overwrites) are expired after 90 days to limit storage cost.
# ---------------------------------------------------------------------------
resource "aws_s3_bucket_lifecycle_configuration" "uploads" {
  bucket = aws_s3_bucket.uploads.id

  # Rule 1 — current object versions: Standard → IA → expire
  rule {
    id     = "hipaa-retention-current"
    status = "Enabled"

    filter { prefix = "" } # Applies to all objects

    transition {
      days          = 90
      storage_class = "STANDARD_IA"
    }

    expiration {
      days = 2555 # 7 years
    }
  }

  # Rule 2 — non-current versions (overwrites/deletes): expire after 90 days
  rule {
    id     = "expire-noncurrent-versions"
    status = "Enabled"

    filter { prefix = "" }

    noncurrent_version_expiration {
      noncurrent_days = 90
    }
  }

  # Rule 3 — incomplete multipart uploads: abort after 7 days (prevents orphan charges)
  rule {
    id     = "abort-incomplete-multipart"
    status = "Enabled"

    filter { prefix = "" }

    abort_incomplete_multipart_upload {
      days_after_initiation = 7
    }
  }
}

# ---------------------------------------------------------------------------
# CORS Configuration
# Allows the React frontend (CloudFront origin) to PUT objects via pre-signed URLs.
# The backend generates the pre-signed URL; the browser uploads directly to S3.
# ---------------------------------------------------------------------------
resource "aws_s3_bucket_cors_configuration" "uploads" {
  bucket = aws_s3_bucket.uploads.id

  cors_rule {
    allowed_headers = ["*"]
    allowed_methods = ["PUT", "POST", "GET", "HEAD"]
    allowed_origins = [
      "https://${aws_cloudfront_distribution.frontend.domain_name}",
      # Allow localhost for local dev — restrict in staging/prod
      "http://localhost:5173",
      "http://localhost:3000",
    ]
    expose_headers  = ["ETag", "x-amz-request-id"]
    max_age_seconds = 3600
  }
}

# ---------------------------------------------------------------------------
# Bucket Policy — restrict all access to the ECS task role
# The backend is the only principal allowed to read/write objects.
# Browsers use pre-signed URLs (signed by the task role credentials).
# ---------------------------------------------------------------------------
resource "aws_s3_bucket_policy" "uploads" {
  bucket = aws_s3_bucket.uploads.id

  # Ensure public access block is applied before the policy
  depends_on = [aws_s3_bucket_public_access_block.uploads]

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Sid    = "AllowECSTaskRoleAccess"
        Effect = "Allow"
        Principal = {
          AWS = aws_iam_role.ecs_task.arn
        }
        Action = [
          "s3:GetObject",
          "s3:PutObject",
          "s3:DeleteObject",
          "s3:GetObjectVersion",
          "s3:ListBucket",
        ]
        Resource = [
          aws_s3_bucket.uploads.arn,
          "${aws_s3_bucket.uploads.arn}/*",
        ]
      },
      {
        Sid    = "DenyNonTLS"
        Effect = "Deny"
        Principal = "*"
        Action    = "s3:*"
        Resource = [
          aws_s3_bucket.uploads.arn,
          "${aws_s3_bucket.uploads.arn}/*",
        ]
        Condition = {
          Bool = {
            "aws:SecureTransport" = "false"
          }
        }
      }
    ]
  })
}

# ---------------------------------------------------------------------------
# Outputs
# ---------------------------------------------------------------------------
output "s3_uploads_bucket_name" {
  description = "S3 uploads bucket name — set as AWS_S3_UPLOADS_BUCKET env var in backend"
  value       = aws_s3_bucket.uploads.id
}

output "s3_uploads_bucket_arn" {
  description = "S3 uploads bucket ARN"
  value       = aws_s3_bucket.uploads.arn
}
